---
test:
  name: Composer Performance test
  description: This is an example Composer perf test
  clients:
    type: local
    number: 1
  rounds:
  - label: vehicle-lifecycle-network
    txNumber:
    - 25
    trim: 0
    rateControl:
    - type: fixed-rate
      opts:
        tps: 5
    arguments:
      testAssets: 25
      transaction: placeOrder
    callback: benchmark/composer/composer-samples/vehicle-lifecycle-network.js
  - label: vehicle-lifecycle-network
    txNumber:
    - 50
    trim: 0
    rateControl:
    - type: fixed-rate
      opts:
        tps: 10
    arguments:
      testAssets: 50
      transaction: scrapVehicle
    callback: benchmark/composer/composer-samples/vehicle-lifecycle-network.js
monitor:
  type:
  - docker
  - process
  docker:
    name:
    - all
  process:
  - command: node
    arguments: local-client.js
    multiOutput: avg
  interval: 1
