version: '2'

networks:
    behave:

services:
    peer1.org2.example.com:
        extends:
            file: docker-compose-base.yml
            service: peer
        container_name: peer0.org3.example.com
        environment:
            - CORE_PEER_CHAINCODELISTENADDRESS=peer0.org3.example.com:7052
            - CORE_PEER_ID=peer0.org3.example.com
            - CORE_PEER_ADDRESS=peer0.org3.example.com:7051
            - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.org3.example.com:7051
            - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.org3.example.com:7051
            - CORE_PEER_GOSSIP_ORGLEADER=true
            - CORE_PEER_GOSSIP_USELEADERELECTION=false
            - CORE_PEER_LOCALMSPID=Org3MSP
            - CORE_PEER_TLS_CLIENTROOTCAS_FILES=/var/hyperledger/users/Admin@org3.example.com/tls/ca.crt
            - CORE_PEER_TLS_CLIENTCERT_FILE=/var/hyperledger/users/Admin@org3.example.com/tls/client.crt
            - CORE_PEER_TLS_CLIENTKEY_FILE=/var/hyperledger/users/Admin@org3.example.com/tls/client.key
            ###NEW REMOVE IF IT DOES NOT WORK
            - CORE_LEDGER_STATE_STATEDATABASE=CouchDB
            - CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=couchdb12:5984
        volumes:
            - ../crypto-config/peerOrganizations/org3.example.com/peers/peer0.org3.example.com/msp:/var/hyperledger/msp
            - ../crypto-config/peerOrganizations/org3.example.com/peers/peer0.org3.example.com/tls:/var/hyperledger/tls
            - ../crypto-config/peerOrganizations/org3.example.com/users:/var/hyperledger/users
            - ../network-config/:/var/hyperledger/configs
            - ../chaincode/fabric:/opt/go/src/github.com/hyperledger/fabric
        extra_hosts:
            - "orderer0.example.com:158.39.75.156"
            - "orderer1.example.com:158.39.75.156"
            - "orderer2.example.com:158.39.75.156"
            - "ca.example.com:158.39.75.156"
            - "peer0.org2.example.com:158.37.63.198"
            - "peer0.org1.example.com:158.37.63.126"
            - "peer1.org1.example.com:158.37.63.234"
            - "peer1.org2.example.com:158.39.75.210"
        depends_on:
            - couchdb12
        networks:
          behave:
             aliases:
               - ${CORE_PEER_NETWORKID}
        ports:
          - 11051:7051
          - 11053:7053

    couchdb12:
        extends:
            file: docker-compose-base.yml
            service: couchdb
        container_name: couchdb12
        # Comment/Uncomment the port mapping if you want to hide/expose the CouchDB service,
        # for example map it to utilize Fauxton User Interface in dev environments.
        ports:
          - "8984:5984"
        networks:
          behave:
             aliases:
               - ${CORE_PEER_NETWORKID}