
version: '2'

services:

    orderer:
        image: hyperledger/fabric-orderer:1.2.0
        environment:
            - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=${CORE_PEER_NETWORKID}_behave
            - ORDERER_GENERAL_LOGLEVEL=debug
            - ORDERER_GENERAL_LOCALMSPID=OrdererMSP
            - ORDERER_GENERAL_LISTENADDRESS=0.0.0.0
            - ORDERER_GENERAL_LISTENPORT=7050
            - ORDERER_GENERAL_LEDGERTYPE=ram
            - ORDERER_GENERAL_GENESISMETHOD=file
            - ORDERER_GENERAL_GENESISFILE=/var/hyperledger/genesis.block
            - CONFIGTX_ORDERER_ORDERERTYPE=solo
            - CONFIGTX_ORDERER_BATCHSIZE_MAXMESSAGECOUNT=${CONFIGTX_ORDERER_BATCHSIZE_MAXMESSAGECOUNT}
            - CONFIGTX_ORDERER_BATCHTIMEOUT=${CONFIGTX_ORDERER_BATCHTIMEOUT}
            - CONFIGTX_ORDERER_ADDRESSES=[127.0.0.1:7050]

        volumes:
            - ../network-config/genesis.block:/var/hyperledger/genesis.block
        working_dir: /opt/gopath/src/github.com/hyperledger/fabric
        command: orderer
        ports:
          - '7050'

    couchdb:
        image: hyperledger/fabric-couchdb

    peer:
        image: hyperledger/fabric-peer:1.2.0
        environment:
            - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
            - CORE_PEER_NETWORKID=${CORE_PEER_NETWORKID}
            - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=${CORE_PEER_NETWORKID}_behave
            - CORE_PEER_ADDRESSAUTODETECT=false
            - CORE_PEER_GOSSIP_ORGLEADER=false
            - CORE_PEER_GOSSIP_USELEADERELECTION=true
            - CORE_PEER_PROFILE_ENABLED=true
            - CORE_LEDGER_STATE_STATEDATABASE=CouchDB
            - CORE_LOGGING_LEVEL=DEBUG
            - CORE_LOGGING_GOSSIP=${CORE_LOGGING_GOSSIP}
            - CORE_LOGGING_MSP=DEBUG
        volumes:
            - /var/run/:/host/var/run/
            - ../network-config/channel.tx:/var/hyperledger/configtx/channel.tx
        command: peer node start
        ports:
            - '7051'
            - '7053'

