---
test:
  clients:
    type: local
    number: 2
  rounds:
  - label: initDevice
    txNumber:
    - 500
    - 500
    - 500
    rateControl:
    - type: fixed-rate
      opts:
        tps: 25
    - type: fixed-rate
      opts:
        tps: 50
    - type: fixed-rate
      opts:
        tps: 75
    callback: benchmark/smarthomes/startDevice.js
  - label: sendReadingPrivate
    txNumber:
    - 500
    - 500
    - 500
    rateControl:
    - type: fixed-rate
      opts:
        tps: 25
    - type: fixed-rate
      opts:
        tps: 50
    - type: fixed-rate
      opts:
        tps: 75
    callback: benchmark/smarthomes/sendReading.js
  - label: query
    txNumber:
    - 100
    rateControl:
    - type: fixed-rate
      opts:
        tps: 50
    - type: fixed-rate
      opts:
        tps: 50
    callback: benchmark/smarthomes/query.js
monitor:
  type:
  - docker
  - process
  docker:
    name:
    - http://158.37.63.126:2376/peer0.org1.example.com
    - http://158.37.63.198:2376/peer0.org2.example.com
    - http://158.39.75.156:2376/orderer0.example.com
    - http://158.39.75.156:2376/zookeeper0
    - http://158.39.75.156:2376/kafka0
  process:
  - command: node
    arguments: local-client.js
    multiOutput: avg
  interval: 1