
version: '2'

networks:
    behave:

services:
    peer0.org1.example.com:
        extends:
            file: docker-compose-base.yml
            service: peer
        container_name: peer0.org1.example.com
        environment:
            - CORE_PEER_CHAINCODELISTENADDRESS=peer0.org1.example.com:7052
            - CORE_PEER_ID=peer0.org1.example.com
            - CORE_PEER_ADDRESS=peer0.org1.example.com:7051
            - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.org1.example.com:7051
            - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.org1.example.com:7051
            - CORE_PEER_GOSSIP_ORGLEADER=${CORE_PEER_GOSSIP_ORGLEADER_PEER0_ORG1}
            - CORE_PEER_GOSSIP_USELEADERELECTION=${CORE_PEER_GOSSIP_USELEADERELECTION_PEER0_ORG1}
            - CORE_PEER_LOCALMSPID=Org1MSP
            - CORE_PEER_TLS_ENABLED=${CORE_PEER_TLS_ENABLED}
            - CORE_PEER_TLS_CERT_FILE=${CORE_PEER_TLS_CERT_FILE}
            - CORE_PEER_TLS_KEY_FILE=${CORE_PEER_TLS_KEY_FILE}
            - CORE_PEER_TLS_ROOTCERT_FILE=/var/hyperledger/tls/ca.crt
        volumes:
            - ../crypto-config/peerOrganizations/org1.example.com/peers/peer0.org1.example.com/msp:/var/hyperledger/msp
            - ../crypto-config/peerOrganizations/org1.example.com/peers/peer0.org1.example.com/tls:/var/hyperledger/tls
            - ../crypto-config/peerOrganizations/org1.example.com/users/Admin@org1.example.com:/var/hyperledger/users/Admin@org1.example.com
            #- ../crypto-config/ordererOrganizations/example.com/orderers:/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/ordererOrganizations/example.com/orderers
            #- ../crypto-config/peerOrganizations:/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations
            - ../network-config/:/var/hyperledger/configs

        extra_hosts:
            - "orderer0.example.com:158.39.77.41"
            - "ca.example.com:158.39.77.41"
            - "peer0.org2.example.com:158.39.77.131"
            - "peer1.org1.example.com:158.39.77.152"
        networks:
          behave:
             aliases:
               - ${CORE_PEER_NETWORKID}
        ports:
          - 7051:7051
          - 7053:7053
