---
test:
  name: fabric-base-240
  clients:
    type: local
    number: 20
  rounds:
  - label: init
    txNumber:
    - 500
    - 500
    - 500
    - 1000
    - 1000
    - 1000
    - 1500
    - 1500
    - 1500
    rateControl:
    - type: fixed-feedback-rate
      opts:
        tps: 25
        unfinished_per_client: 25
    - type: fixed-feedback-rate
      opts:
        tps: 50
        unfinished_per_client: 50
    - type: fixed-feedback-rate
      opts:
        tps: 75
        unfinished_per_client: 75
    - type: fixed-feedback-rate
      opts:
        tps: 25
        unfinished_per_client: 25
    - type: fixed-feedback-rate
      opts:
        tps: 50
        unfinished_per_client: 50
    - type: fixed-feedback-rate
      opts:
        tps: 75
        unfinished_per_client: 75
    - type: fixed-feedback-rate
      opts:
        tps: 25
        unfinished_per_client: 25
    - type: fixed-feedback-rate
      opts:
        tps: 50
        unfinished_per_client: 50
    - type: fixed-feedback-rate
      opts:
        tps: 75
        unfinished_per_client: 75
    callback: benchmark/smarthomes/sendReading.js
monitor:
  type:
  - docker
  docker:
    name:
    - http://158.37.63.126:2376/peer0.org1.example.com
    - http://158.37.63.234:2376/peer1.org1.example.com
    - http://158.37.63.198:2376/peer0.org2.example.com
    - http://158.39.75.210:2376/peer1.org2.example.com
    - http://158.37.63.35:2376/peer0.org3.example.com
    - http://158.39.75.156:2376/orderer0.example.com
    - http://158.39.75.156:2376/orderer1.example.com
    - http://158.39.75.156:2376/orderer2.example.com
    - http://158.39.75.156:2376/zookeeper0
    - http://158.39.75.156:2376/zookeeper1
    - http://158.39.75.156:2376/zookeeper2
    - http://158.39.75.156:2376/kafka0
    - http://158.39.75.156:2376/kafka1
    - http://158.39.75.156:2376/kafka2
    - http://158.39.75.156:2376/kafka3
  process:
  - command: node
    arguments: local-client.js
    multiOutput: avg
  interval: 1
