---
test:
  clients:
    type: local
    number: 5
  rounds:
  - label: init
    txNumber:
    - 100
    rateControl:
    - type: fixed-rate
      opts:
        tps: 75
    callback: benchmark/smarthomes/init.js
  - label: query
    txNumber:
    - 5
    rateControl:
    - type: fixed-rate
      opts:
        tps: 5
    - type: fixed-rate
      opts:
        tps: 5
    callback: benchmark/smarthomes/query.js
monitor:
  type:
  - docker
  docker:
    name:
    - http://158.39.77.58:2376/peer0.org1.example.com
    - http://158.39.77.152:2376/peer1.org1.example.com
    - http://158.39.77.131:2376/peer0.org2.example.com
    - http://158.39.77.41:2376/orderer0.example.com
  process:
  - command: node
    arguments: local-client.js
    multiOutput: avg
  interval: 1