---
test:
  name: smarthomes
  description: This is smarthomes benchmark for caliper
  clients:
    type: local
    number: 5
  rounds:
  - label: init
    txNumber:
    - 100
    rateControl:
    - type: fixed-rate
      opts:
        tps: 20
    arguments:
      accounts: 4
      txnPerBatch: 1
    callback: benchmark/smarthomes/init.js
  - label: sendReading
    txNumber:
    - 100
    rateControl:
    - type: fixed-rate
      opts:
        tps: 50
    callback: benchmark/smarthomes/sendReading.js
  - label: query
    txNumber:
    - 50
    rateControl:
    - type: fixed-rate
      opts:
        tps: 50
    callback: benchmark/smarthomes/query.js
monitor:
  type: 
  - docker
  docker:
    name:
    - peer0.org1.example.com
    - peer2.org1.example.com
    - peer0.org2.example.com
    - orderer0.example.com
  process:
  - command: node
    arguments: local-client.js
    multiOutput: avg
  interval: 1
