---
test:
  name: smarthomes
  description: This is smarthomes benchmark for caliper
  clients:
    type: local
    number: 5
  rounds:
  - label: smallOperations
    txNumber:
    - 5
    rateControl:
    - type: fixed-rate
      opts:
        tps: 20
    arguments:
      accounts: 4
      txnPerBatch: 1
    callback: benchmark/smarthomes/init.js
  - label: query
    txNumber:
    - 5
    rateControl:
    - type: fixed-rate
      opts:
        tps: 50
    callback: benchmark/smallbank/query.js
monitor:
  type: docker
  docker:
    name:
    - all
  interval: 1
