
version: '2'

networks:
    behave:

services:
    peer0.org1.example.com:
        extends:
            file: docker-compose-base.yml
            service: peer
        container_name: peer0.org1.example.com
        environment:
            - CORE_PEER_CHAINCODELISTENADDRESS=peer0.org1.example.com:7052
            - CORE_PEER_ID=peer0.org1.example.com
            - CORE_PEER_ADDRESS=peer0.org1.example.com:7051
            - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.org1.example.com:7051
            - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.org1.example.com:7051
            - CORE_PEER_GOSSIP_ORGLEADER=${CORE_PEER_GOSSIP_ORGLEADER_PEER0_ORG1}
            - CORE_PEER_GOSSIP_USELEADERELECTION=${CORE_PEER_GOSSIP_USELEADERELECTION_PEER0_ORG1}
            - CORE_PEER_LOCALMSPID=Org1MSP
            #REMOVE IF IT DOES NOT WORK
            - CORE_LEDGER_STATE_STATEDATABASE=CouchDB
            - CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=couchdb01:5984
        volumes:
            - ../crypto-config/peerOrganizations/org1.example.com/peers/peer0.org1.example.com/msp:/var/hyperledger/msp
            - ../crypto-config/peerOrganizations/org1.example.com/peers/peer0.org1.example.com/tls:/var/hyperledger/tls
            - ../crypto-config/peerOrganizations/org1.example.com/users:/var/hyperledger/users
            - ../network-config/:/var/hyperledger/configs
            - ../chaincode/fabric/core/chaincode/lib/cid:/opt/go/src/github.com/hyperledger/fabric/chaincode/lib/cid
            - ../chaincode/fabric/vendor/github.com/pkg:/opt/go/src/github/pkg
        extra_hosts:
            - "orderer0.example.com:158.39.75.156"
            - "orderer1.example.com:158.39.75.156"
            - "orderer2.example.com:158.39.75.156"
            - "ca.example.com:158.39.75.156"
            - "peer0.org2.example.com:158.37.63.198"
            - "peer1.org1.example.com:158.37.63.234"
            - "peer1.org2.example.com:158.39.75.210"
            - "peer0.org3.example.com:158.37.63.35"
        depends_on:
            - couchdb01
        networks:
          behave:
             aliases:
               - ${CORE_PEER_NETWORKID}
        ports:
          - 7051:7051
          - 7053:7053
    
    couchdb01:
        extends:
            file: docker-compose-base.yml
            service: couchdb
        container_name: couchdb01
        # Comment/Uncomment the port mapping if you want to hide/expose the CouchDB service,
        # for example map it to utilize Fauxton User Interface in dev environments.
        ports:
          - "5984:5984"
        networks:
          behave:
             aliases:
               - ${CORE_PEER_NETWORKID}