
version: '2'

networks:
    behave:

services:
    peer1.org2.example.com:
        extends:
            file: docker-compose-base.yml
            service: peer
        container_name: peer1.org2.example.com
        environment:
            - CORE_PEER_CHAINCODELISTENADDRESS=peer1.org2.example.com:7052
            - CORE_PEER_ID=peer1.org2.example.com
            - CORE_PEER_ADDRESS=peer1.org2.example.com:7051
            - CORE_PEER_GOSSIP_BOOTSTRAP=peer1.org2.example.com:7051
            - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer1.org2.example.com:7051
            - CORE_PEER_GOSSIP_ORGLEADER=${CORE_PEER_GOSSIP_ORGLEADER_PEER0_ORG1}
            - CORE_PEER_GOSSIP_USELEADERELECTION=${CORE_PEER_GOSSIP_USELEADERELECTION_PEER0_ORG1}
            - CORE_PEER_LOCALMSPID=Org2MSP
            - CORE_PEER_TLS_CLIENTROOTCAS_FILES=/var/hyperledger/users/Admin@org1.example.com/tls/ca.crt
            - CORE_PEER_TLS_CLIENTCERT_FILE=/var/hyperledger/users/Admin@org2.example.com/tls/client.crt
            - CORE_PEER_TLS_CLIENTKEY_FILE=/var/hyperledger/users/Admin@org2.example.com/tls/client.key
            ###NEW REMOVE IF IT DOES NOT WORK
            - CORE_LEDGER_STATE_STATEDATABASE=CouchDB
            - CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=couchdb12:5984
        volumes:
            - ../crypto-config/peerOrganizations/org2.example.com/peers/peer1.org2.example.com/msp:/var/hyperledger/msp
            - ../crypto-config/peerOrganizations/org2.example.com/peers/peer1.org2.example.com/tls:/var/hyperledger/tls
            - ../crypto-config/peerOrganizations/org2.example.com/users:/var/hyperledger/users
            - ../network-config/:/var/hyperledger/configs
        extra_hosts:
            - "orderer0.example.com:158.39.48.98"
            - "orderer1.example.com:158.39.48.98"
            - "orderer2.example.com:158.39.48.98"
            - "ca.example.com:158.39.48.98"
            - "peer0.org2.example.com:158.39.77.131"
            - "peer0.org1.example.com:158.39.77.58"
            - "peer1.org1.example.com:158.39.77.152"
        depends_on:
            - couchdb12
        networks:
          behave:
             aliases:
               - ${CORE_PEER_NETWORKID}
        ports:
          - 10051:7051
          - 10053:7053

    couchdb12:
        extends:
            file: docker-compose-base.yml
            service: couchdb
        container_name: couchdb12
        # Comment/Uncomment the port mapping if you want to hide/expose the CouchDB service,
        # for example map it to utilize Fauxton User Interface in dev environments.
        ports:
          - "8984:5984"
        networks:
          behave:
             aliases:
               - ${CORE_PEER_NETWORKID}